CHANGELOG.md, charts/pie/CHANGELOG.md
Version 0.1.0 was once released at the following commit. 69cf6fc908a4b057d0840b8c8953e7d6882276c4
However, there was a mistake on this release.
This commit fix it.
=> Bump version to 0.1.0

charts/pie/templates/deployment.yaml, charts/pie/values.yaml, cmd/controller.go, controllers/node_controller.go, controllers/node_controller_test.go, controllers/storageclass_controller_test.go
This PR changes the option to exclude inappropriate nodes. By using this option, for example, nodes with the taint that should not be the target of pie can be excluded.
=> enhance node selector to fix jobs or pods pending

controllers/event_controller.go
This PR fixes the following error by ignoring not found error because old events may refer the deleted pod.
```
1.6686630294454665e+09  ERROR   event-reconciler        failed to name of node and storage class related to the pod     {"pod": "pie-probe-10.69.1.139-ceph-canary-block-be4f7f-27807946-tc8sw", "error": "Pod \"pie-probe-10.69.1.139-ceph-canary-block-be4f7f-27807946-tc8sw\" not found"}
github.com/topolvm/pie/controllers.(*EventReconciler).SetupWithManager.func1.1
/work/controllers/event_controller.go:170
github.com/topolvm/pie/controllers.(*EventReconciler).SetupWithManager.func1
/work/controllers/event_controller.go:201
```
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
Co-authored-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
=> fix the occasion of getNodeNameAndStorageClass error message

index.yaml
The current Helm Chart `index.yaml` contains a version that doesn't exist, which is causing an error in artifacthub's repository registration.
So we need to delete this non-existing version from `index.yaml`.
https://github.com/topolvm/pie/blob/gh-pages/index.yaml#L70-L80
- https://github.com/topolvm/pie/pull/39
=> Remove the not found version from index.yaml

charts/pie/templates/role.yaml, config/rbac/role.yaml, constants/constants.go, controllers/node_controller.go, controllers/pod_controller.go, controllers/provision_observer.go
Pie has the ability to delete Pods that have not started within a
certain period of time. If a Pod does not start, there may be a problem,
and we do not want to have Pods being created over and over again.
In this commit, we change so that if a Pod does not start within a
certain period of time, the Jobs in the ownerReferences will be deleted
instead of the Pod.
=> observer: delete Job instead of Pod after create threshold

controllers/node_controller.go
To ensure that cronjobs are deleted when the pie is deleted, ownerReferences to the pie pod were set in the cronjobs. However, when a pie update occurred, the old pod was deleted and the cronjobs were deleted simultaneously. This deletion was causing high loads.
In this PR, the ownerReference was deleted to avoid high loads.
=> Remove ownerReference

controllers/provision_observer.go
client.Delete() cannot accept nil as its third argument.
Signed-off-by: Yuma Ogami <yuma-ogami@cybozu.co.jp>
Co-authored-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
=> Fix k8s clinet.Delete() argument.

README.md, controller/metrics.go, controllers/provision_observer.go, docs/design.md, e2e/suite_test.go
Currently we have two kinds of metrics to track slow/fast probe. It's difficult to use from promql. So unify these two labels and distinguish slow/fast by the dedicated label.
=> change the spec of metrics

probe/diskmetrics.go
fio outputs some warnings to its stderr, but it is less useful. By embeding it in the error, the message will appear if the command fails.
=> Embed stderr from running command in error

charts/pie/templates/deployment.yaml, charts/pie/values.yaml, cmd/controller.go
It it useful to debug a bug that only happens after long running. The function is disabled by default because it is not needed for normal usage.
=> Add pprof function

charts/pie/templates/role.yaml, config/rbac/role.yaml, constants/constants.go, controllers/node_controller.go, controllers/pod_controller.go, controllers/provision_observer.go, e2e/suite_test.go
We store pods event times to maps and delete them if pods are deleted. But we misunderstood the controller-runtime delete events that do not provide object names, the deletion did not work. This PR leverages a finalizer to get object names properly.
=> Fix map growing

.github/workflows/release.yaml, CHANGELOG.md, RELEASE.md, charts/pie/CHANGELOG.md
Stop using the `CHANGELOG.md`,
and use release notes instead.
Similar PR for topolvm: https://github.com/topolvm/topolvm/pull/765
Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>
=> Stop using the `CHANGELOG.md`

Makefile, docs/maintenance.md, e2e/Makefile, versions.mk
The pie project uses many tools and their versions are scattered in many places. It is a burden for us to update them, so we merge them into a single versoins.mk file.
=> Merge versions together into versions.mk

versions.mk
In 555522d (Merge versions together into versions.mk, 2023-11-02), The regression that prevents the kubernetes version from setting via the environment variable was introduced, so CI can not specify the version. This commit allows it as before.
=> Fix to set KUBERNETES_VERSION by the environment variable

.github/workflows/create-chart-update-pr.yaml, .github/workflows/project-bot.yaml
- fix deprecated notation of app-id and private-key
- use Github App token to create chart release PR
=> Use Github App token to create chart release PR

charts/pie/templates/pie.topolvm.io_pieprobes.yaml, test/e2e/testdata/pieProbe.yaml
In pull request #101, we introduced a new custom resource called PieProbe. However, the charts/ and test/e2e/ directories were not synchronized with the auto-generated config/ directory.
This patch fixes the above probelm, by copying the latest PieProbe CRD from config/ to charts/ and updating the manifests used in the e2e tests.
=> charts, test/e2e: synchronize PieProbe CRD

Makefile, versions.mk
Currently, the CI is broken because the latest setup-envtest requires go 1.21 ([an example failed run](https://github.com/topolvm/pie/actions/runs/8479380821/job/23286909812)). This patch solves this problem by pinning setup-envtest to go 1.20.
See also:
- https://github.com/topolvm/topolvm/pull/865
- https://github.com/kubernetes-sigs/controller-runtime/issues/2744
=> pin setup-envtest to go 1.20

internal/controller/provision_observer2.go, test/e2e/suite_test.go
The new provision observer (provision_observer2.go) introduced in #101 tries to remove the owned jobs that are failing for a while, but it doesn't work well because it looks for them by a wrong prefix.
This PR fixes the above problem by using constants.MountProbeNamePrefix and constants.ProvisionProbeNamePrefix instead of constants.ProbeNamePrefix when the provision observer looks for the failing jobs.
=> fix provision_observer2 to delete failing Jobs correctly

internal/controller/pie/pieprobe_controller.go
When the current implementation decides on a cronjob name, it uses at most 11 letters for a node name. This behaviour is problematic when a node name is an IP address, which can be at most 15 (= 3*4+3) letters. This commit fixes this problem by including at most 15 letters of the node name in the cronjob name. In compensation, this commit shrinks the length of the storage class name from 14 to 12.
A mount cronjob name (at most 40 letters) consists of:
- "provision-" (10 letters)
- PieProbe resource name (at most 10 letters)
- hyphen (1 letter)
- StorageClass name (at most 12 letters)
- hyphen (1 letter)
- hash (6 letters)
A provision cronjob name (at most 52 letters) consists of:
- "mount-" (6 letters)
- PieProbe resource name (at most 10 letters)
- hyphen (1 letter)
- Node name (at most …
=> fix: use at most 15 letters for node name in cronjob name

api/pie/v1alpha1/pieprobe_types.go, charts/pie/templates/pie.topolvm.io_pieprobes.yaml, config/crd/bases/pie.topolvm.io_pieprobes.yaml, internal/controller/pie/pieprobe_controller.go, internal/controller/pie/pieprobe_controller_test.go
Currently, when a user deploys a PieProbe object, both of provision and
mount probes are deployed. However, under some circumstances, it is
enough to deploy either provision probes or mount probes only.
This commit supports deploying either provision probes or mount probes
only, by adding disableProvisionProbes and disableMountProbes fields to
PieProbe spec.
Signed-off-by: Ryotaro Banno <ryotaro.banno@gmail.com>
=> Support deploying provision probe or mount probe only

internal/controller/pie/pieprobe_controller.go
The current implementation of createOrUpdateJob prints "createOrUpdate" and "createOrUpdateJob Finished" info logs every time the function runs, both before and after execution. Since this function is called repeatedly from the reconciliation loop, these logs are generated excessively. However, they don't provide any meaningful information and clutter the log readability.
This commit removes these logs to make the logs for pie much clearer.
=> stop logging of createOrUpdateJob
